/* client-main.h */

#ifndef	DEFAULT_SERVER_PORT
#define DEFAULT_SERVER_PORT	22233
#endif

#ifndef	DEFAULT_SERVER_IP
#define	DEFAULT_SERVER_IP	"127.0.0.1" //linux17.csie.org
#endif

#define BUFFER_SIZE		2000
#define FILESEG_LIMIT_LEN	1000
#define MESSAGE_LIMIT_LEN	1000
#define FILENAME_LIMIT_LEN	500
#define USERNAME_LIMIT_LEN	100
#define PASSWORD_LIMIT_LEN	100
#define TAG_LIMIT_LEN		20
